--- # This is a structural YAML example to install APACHE2 on UBUNTU
- hosts: ubuntu
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: myuser
  tasks:
  - name: Install apache2 server on Ubuntu nodes
    apt:
      name: apache2
      state: latest
    notify:
    - startservice
  handlers:
  - name: startservice
    service:
      name: apache2
      state: restarted
