--- # Testing how variables work in the vars section of a playbook
- hosts: '{{ myhosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  tasks:
  - name: Install the indicated software
    apt:
      name: '{{ pkg }}'
      state: latest
